### PR TITLE
Adding Cloudsmith Registry

### PR DESCRIPTION
**Pull request by apoclyps**
### What's Changed

Adds support for the [Cloudsmith](https://cloudsmith.io/) Docker Registry.

> Cloudsmith provides open-source, public, and private [docker registries](https://help.cloudsmith.io/docs/docker-registry-overview) compatible with the V2 API for [schema 1](https://docs.docker.com/registry/spec/manifest-v2-1/), [schema 2](https://docs.docker.com/registry/spec/manifest-v2-2/), and [v2.1+OCIv1 manifests](https://github.com/opencontainers/image-spec) image manifests. 

Screenshot 2020-04-20 at 16 53 55

### Steps to Test

1. Create an account on [Cloudsmith](https://cloudsmith.io/user/signup/) 
2. Create a [repository](https://help.cloudsmith.io/docs/create-a-repository) e.g. `testing-private`
3. Context documentation is available at https://cloudsmith.io/~USERNAME/repos/testing-private/upload/#docker-native where `USERNAME` is the name of the user created.
4. Within the extension development environment, open `Docker Registries: Connect Registry....`
5. Select `Cloudsmith` as the registry provider
6. Enter your repository URL (replacing with your username and repository ensuring the trailing slash is provided) e.g. `https://docker.cloudsmith.io/v2/USERNAME/REPOSITORY/`
7. Enter your cloudsmith username
8. Enter your cloudsmith password or [API Key](https://cloudsmith.io/user/settings/api/)
9. Cloudsmith can now be found within Registries

**Setup Video**
[](http://www.youtube.com/watch?v=Xml0L0RhGQg "Setup")

### CODE REVIEW

**Comment by bwateratmsft** [comment]
Thank you for the submission @apoclyps! Your change actually gives me an idea that would allow us to improve the generic `DockerV2` registry provider significantly, while also simplifying the code to add Cloudsmith (and maybe unblocking GitHub as well). I need to spend some time thinking and testing around, I'll get back to you soon.

**Comment by lskillen** [comment]
@bwateratmsft It would be *fantastic* to see this merged as generic support is worked towards, especially as we've got users asking for it. 🙏 

Some of the functionality of Cloudsmith differs a little (esp. around authorisation), which is why we had to make some changes on our side to adapt; we're very willing to help collaborate on it for the next refactor!

**Comment by BigMorty** [comment]
@apoclyps - My name is Mike Morton and I am the program manager on the Docker extension here at Microsoft. This PR has brought to our attention that the current way of adding registries to the extension does not scale well. We are in the middle or designing how we plan to support this going forward. As soon as we finalize the design we will share it with you so you can change to use the new design.

**Comment by bwateratmsft** [comment]
@apoclyps @lskillen We've been doing some discussion and planning for a while, and have come up with a proposed extensibility model: #2033

We'd love to get your feedback on it!

**Comment by bwateratmsft** [comment]
For now I'll close this. We'd love to hear your thoughts on our registry extensibility proposal: #2033

**Comment by lskillen** [comment]
@bwateratmsft Not a problem! I believe Kyle has been interacting elsewhere. We're happy to try and fit it into the new system, and we'll certainly be offering suggestions if required. Thank you for your help. :-)

**Comment by bwateratmsft** [comment]
@lskillen Glad to help! We have started work on the new model but want to make sure we hear from more than just ourselves before we start putting it into the code. Interfaces are hard to change once they are in use by outside parties, so we want to be sure we get it right (or as close as possible) the first time. :smile:

**Comment by lskillen** [comment]
@bwateratmsft Maybe a good time to reconsider? :)

**Comment by bwateratmsft** [comment]
We still wanna do the registry extensibility model, but other things have been prioritized, like the ACI or Docker contexts work, or me being on parental leave last winter (and soon, again! 👶 x 2).

**Comment by lskillen** [comment]
> We still wanna do the registry extensibility model, but other things have been prioritized, like the ACI or Docker contexts work, or me being on parental leave last winter (and soon, again! 👶 x 2). We definitely haven't forgotten and it's still important to me.

Ha! 🎉 There's nothing better. :-) Equal 2x Proud Dad over here. So a huge congratulations there (2x)! 😁 

No problem at all. This was just a friendly poke; I know you'll do right by us when you get the chance. Enjoy the parental leave!

**Pull request closed without merging**
