### PR TITLE
Simplify Notified Doctor

### PR DESCRIPTION
**Pull request by Infraton11**
<luab'shawl ><iota' amingesa>

### CODE REVIEW

**Comment by Infraton11** [comment]
**BOLD**

**Comment by Infraton11** [comment]
> [CLA assistant check](https://cla.opensource.microsoft.com/microsoft/vscode-docker?pullRequest=1145) 
> All CLA requirements met.


Im going to try and do a liittle of a relaxation technique

**Comment by Infraton11** [comment]
I would say congratulations to those of thrust into the wild and impact so graceful ont the surface of the earth.Amen

**Comment by EricJizbaMSFT** [comment]
@Infraton11 please add more description on what you're changing and why

Also...
question
...are you a bot?

**Comment by StephenWeatherford** [comment]
Do not feed the bots!

#TurningTestFail

**Pull request closed without merging**
