### PR TITLE
Upgrade language server version to 0.0.21

### LINKED ISSUE #952: Update language server version for fix: Dockerfile linting problems with variables in RUN instructions
Im running VSCode 
```
Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
```
When i writing Dockerfile with escape=` i always get "lint" error in file - see below image.
image

Here you can see in dockerfile that it indicate error
image

I can build docker image still - but i guess this has something todo with vscode-docker extension and linting?

### PR DESCRIPTION
**Pull request by rcjsuen**
This new update is mainly focused around improvements to the validation to correct some false positives (fixes #952) in addition to a fix to how variables were being resolved. Now the language server only considers alphanumeric and underscore characters as part of a variable's name.

As always, please use the following Dockerfile before and after the pull request to verify the changes:
```Dockerfile
# VOLUME fixes -------------------------------------------------
FROM node
# hover over VOLUME, there is a typo "specifid" that is now fixed
VOLUME [ "/data" ]
# invoke Intellisense here, the documentation has the same typo "specifid" that is now fixed
VOL

# RUN instruction linting fixes --------------------------------
FROM scratch
# there was an error on the question mark, this is now fixed
RUN echo ${bbb:?}

# there was an error on the "T", this is now fixed
# see https://github.com/microsoft/vscode-docker/issues/952
RUN echo ${Env:Temp}

# FROM linting fixes -------------------------------------------
# there was no error before, now this will be properly flagged as being an invalid base image
FROM $image

# variable resolution linting fixes ----------------------------
FROM scratch
ARG ARG_VAR=1234
ENV ENV_VAR $ARG_VAR
# "$ENV_VAR" was incorrectly highlighted as an error, now it's okay
EXPOSE "$ENV_VAR"

FROM scratch
ARG ARG_VAR=1234
# "$ARG_VAR" was incorrectly highlighted as an error, now it's okay
EXPOSE "$ARG_VAR"

# variable resolution fixes ------------------------------------
FROM alpine
ENV var value
# put your cursor in $var, the whole $var:test gets highlighted
# now it only highlights $var
RUN echo $var:test

FROM alpine
ENV var value
# put your cursor in $var, hit F2 to rename, it used to
# show var:test, now it only shows var
RUN echo $var:test

FROM alpine
ENV var value
# put your cursor in $var, hit F2 to rename, rename the variable,
# only the RUN gets modified, the ENV declaration should get modified also
RUN echo $var:test

FROM alpine
ENV var value
# put your cursor in $var, hit F12 to open the definition,
# nothing happens, now it will jump to the variable declaration
RUN echo $var:test

FROM alpine
ENV var value
# hover your cursor over $var, nothing is shown, now it resolve correctly
# and show "value"
RUN echo $var:test
```

### CODE REVIEW

**Comment by rcjsuen** [comment]
@EricJizbaMSFT Thanks for reviewing this! Have a nice weekend!

**Comment by bverkron** [comment]
Trying to track down the source of my issue and the trail has led me here. Is the following something that should be solved by this PR or is it something else?

image

**Comment by bverkron** [comment]
Fair point, but should the syntax highlighting / error checking recognize the escape command and adjust accordingly? It does not seem to.

**Comment by rcjsuen** [comment]
> Fair point, but should the syntax highlighting / error checking recognize the escape command and adjust accordingly? It does not seem to.

The linting feature should recognize your parser directive if you have defined one. I suggest you open a new issue if you are still seeing issues.

As to the syntax highlighting, the language server is not doing the calculations there. See #75 and #292.

**Pull request merged**
