### PR TITLE
Upgrade to language server 0.4.1

### PR DESCRIPTION
**Pull request by rcjsuen**
This release comes with a few fixes for some false positives in the linter and an infinite loop fix for semantic tokens. It also comes with some very rudimentary support for code completion based on `WORKDIR` instructions.

Please use the Dockerfiles below for testing.

```Dockerfile
# ARG now supports multiple arguments
# https://github.com/microsoft/vscode-docker/issues/2760
FROM scratch
ARG a=b b

# ${env:variable} is no longer flagged as an error
# https://github.com/microsoft/vscode-docker/issues/2738
ENTRYPOINT powershell -Command \
    kubectl port-forward --address ${env:address} pod/${env:podname} ${env:source}:${env:dest} -n ${env:namespace}
CMD powershell -Command \
    kubectl port-forward --address ${env:address} pod/${env:podname} ${env:source}:${env:dest} -n ${env:namespace}

# ? modifiers will no longer be flagged as an error
ENV FOO=${FOO:?}

# labels will no longer be incorrectly flagged as missing names
# https://github.com/microsoft/vscode-docker/issues/2865
LABEL "com.github.actions.name"="Spell Checker"\
 "com.github.actions.description"="Check repository for spelling errors"\
 "com.github.actions.icon"="edit-3"\
 "com.github.actions.color"="red"\
 "repository"="http://github.com/check-spelling/check-spelling"\
 "homepage"="http://github.com/check-spelling/check-spelling/tree/master/README.md"\
 "maintainer"="Josh Soref <jsoref@noreply.users.github.com>"
```
```Dockerfile
# this Dockerfile will no longer cause an infinite loop when calculating semantic. tokens
# https://github.com/microsoft/vscode-docker/issues/2055#issuecomment-663295938
FROM alpine
ENV kkk \
        vvv \
        # comment
        # comment
        # comment
        # comment
        vvv2
```
```Dockerfile
FROM alpine
WORKDIR /a/b/c
WORKDIR d
# add "a" to the end of the next line to get some rudimentary code completion support
# part of a multi-phased work needed for https://github.com/microsoft/vscode-docker/issues/2537
COPY test.txt /
```
image

### CODE REVIEW

**Comment by rcjsuen** [comment]
A regression was introduced in 0.4.0 which is now fixed in 0.4.1 so I've updated the title (but not the branch name as the pull request relies on that).

**Review by bwateratmsft — APPROVED** [review]
Awesome as always @rcjsuen! Everything worked like a charm.

The path intellisense is really cool! @ucheNkadiCode, check it out!

**Comment by bwateratmsft** [comment]
@rcjsuen one quick question, there's a few different versions of `dockerfile-utils` and `dockerfile-ast` being included.

`dockerfile-language-server-nodejs` includes:
```json
  "dependencies": {
    "dockerfile-language-service": "0.3.0",
    "dockerfile-utils": "0.2.0",
    "vscode-languageserver": "^7.0.0"
  },
```

`dockerfile-language-service` includes:
```json
  "dependencies": {
    "dockerfile-ast": "0.2.0",
    "dockerfile-utils": "0.4.2",
    "vscode-languageserver-types": "3.17.0-next.1"
  },
```

If I'm reading the package-lock.json right, it's resulting in both `dockerfile-utils` 0.4.2 and 0.2.0, `dockerfile-ast` 0.2.1 and 0.2.0, and maybe also some duplicates of `vscode-languageserver*`. Is this intentional?

**Comment by rcjsuen** [comment]
> If I'm reading the package-lock.json right, it's resulting in both `dockerfile-utils` 0.4.2 and 0.2.0, `dockerfile-ast` 0.2.1 and 0.2.0, and maybe also some duplicates of `vscode-languageserver*`. Is this intentional?

@bwateratmsft That should be fine. It's not the first time that the versions haven't lined up perfectly between the server and the service.

I'll change my approach going forward (as it is something that bothers me every time I make a release) but I do not believe this should cause any issues.

**Pull request merged**
