### PR TITLE
Add `registryName` to the ACA contract

### PR DESCRIPTION
**Pull request by MicroFish91**
My interpretation of what needed to change to support [this](https://github.com/microsoft/vscode-azurecontainerapps/pull/229#discussion_r1067151186).  Let me know if I was off or on the ball :)

### CODE REVIEW

**Comment by bwateratmsft** [comment]
How do login server and registry differ? Are they different just for individual cases (e.g. Docker Hub) or more generally?

**Comment by MicroFish91** [comment]
For **ACR**: From what I remember, `loginServer` parameter currently comes in as undefined for ACR stuff via contract; however, at its core the `registryName` should be no different than the `loginServer` here.

For **Docker Hub** it will come in as:
loginServer: index.docker.io
registryName: docker.io

**GitLabs**
They are the same.

**Comment by bwateratmsft** [comment]
If Docker Hub is the only one that needs special casing of login vs. registry, I think it's best to just send registry, and have ACA break it into the two arguments to supply to the deployment

**Comment by MicroFish91** [comment]
Are you opposed to keeping the contract how it was then?  I could just parse from the entire `imageName` but use stricter RegEx.

For ACR: `/\.azurecr\.io\//i`

For Docker Hub:  `/^docker\.io/i`?

**Pull request closed without merging**
