### PR TITLE
Add a step to open a folder at the beginning

### LINKED ISSUE #3223: Show an "Open Folder" step before running image, if no workspace is open
Additionally, might need to change verbiage on "Now that you've built an image..."

### PR DESCRIPTION
**Pull request by bwateratmsft**
Fixes #3223.

image

### CODE REVIEW

**Comment by bwateratmsft** [comment]
TODO: Should we change the verbiage on the "Run container" step to not refer back to previous steps that may or may not exist?

**Review by karolz-ms — APPROVED** [review]
Nice

**Comment by ucheNkadiCode** [comment]
> the verbiage on the "Run container" step t

I'm not understanding which steps WOULD NOT exist before "Run containers". Wouldn't that be to create a dockerfile?

**Comment by bwateratmsft** [comment]
@ucheNkadiCode if no workspace is open, "Add Dockerfiles" and "Build Image" will not show up because it isn't possible for them to succeed. So, that would make "Run containers" the first step, and the prose would begin with "Now that you've built an image..."

**Comment by bwateratmsft** [comment]
Screenshots for the new verbiage @ucheNkadiCode came up with:

image
image

**Pull request merged**
