### PR TITLE
Update Docker templates for .NET Core to bring parity with Visual Studio 2017

### PR DESCRIPTION
**Pull request by spboyer**
Partially addresses #56 

There are 2 pieces that need to be added.

1. launch.json needs to be created or inserted (if exists)
2. tasks.json needs to be created or inserted (if exists)

tasks.json - https://github.com/spboyer/dockerdebugapp/blob/master/.vscode/tasks.json
launch.json - https://github.com/spboyer/dockerdebugapp/blob/master/.vscode/launch.json

Need API help for 'Add configuration' for these.

@chrisdias @SteveLasker

### CODE REVIEW

**Comment by chrisdias** [comment]
Thanks for the PR!

Can we separate this out into changes for the dockerfile for .NET and the generation of the PS and bash scripts?  When we first added support for commands we explicitly didn't include these scripts as they are mostly exposed through commands in the extension. Could we instead look at improving  the extension (e.g. settings) to provide any missing support that the scripts provide?

//cc @lostintangent

**Comment by galvesribeiro** [comment]
Guys, did you saw my last comment on #56? We don't need scripts at all.

**Comment by spboyer** [comment]
@galvesribeiro What @chrisdias is saying here is to do it in steps. Let's update the Dockerfile(s) for .NET Core and then update the built in commands for to add the configurations for the launch.json and tasks.json. 

It's a combination of both solutions, but with some simplicity.

**Comment by galvesribeiro** [comment]
AH ok.

> Can we separate this out into changes for the dockerfile for .NET and the generation of the PS and bash scripts?

This question mislead me to think that you guys would still use that PS/bash scripts. Sorry :)

**Comment by galvesribeiro** [comment]
Will it not be merged/fixed?

**Pull request closed without merging**
