### PR TITLE
Allow custom values for COMPOSE_FILE_GLOB_PATTERN and DOCKERFILE_GLOB_PATTERN (issue #102)

### LINKED ISSUE #102: Allow custom file names
[Right now, `COMPOSE_FILE_GLOB_PATTERN` and `DOCKERFILE_GLOB_PATTERN` are hardcoded patterns](https://github.com/Microsoft/vscode-docker/blob/91a56df16058eaa134855eb2438be4216fa2b74d/dockerExtension.ts#L29-L30).

We'd need a way to configure those, either by user or by project.

Thanks!

### PR DESCRIPTION
**Pull request by x13machine**
* add setting docker.dockerfileGlobPattern for specifying COMPOSE_FILE_GLOB_PATTERN
* add setting docker.composeFileGlobPattern for specifying COMPOSE_FILE_GLOB_PATTERN 
* add information about the settings in README.md 

Fixes #102

### CODE REVIEW

**Comment by x13machine** [comment]
oh there's a pull request for something similar. I'll look at that tomorrow.

**Comment by PrashanthCorp** [comment]
@x13machine , 

Thanks for the PR! I've edited the description to refer to the issue it addresses. 

I don't have a pull request on that yet, I have a commit on it as part of another branch I'm working on: 
https://github.com/Microsoft/vscode-docker/commit/3e0b8143ab7bb8b04e58580ddd4d1a13ae743d24

**Comment by x13machine** [comment]
@PrashanthCorp I was talking about #248. I looked it and it does something different.

**Comment by PrashanthCorp** [comment]
That PR does not make the glob_pattern configurable. See https://github.com/Microsoft/vscode-docker/pull/248#issuecomment-404947976 for more context.

**Comment by bwateratmsft** [comment]
I'll close this since #1825 does this.

**Pull request closed without merging**
