### PR TITLE
Add networks view.

### PR DESCRIPTION
**Pull request by stuartthomson**
Add two commands:
- Prune networks
- Remove network
Upgrade dockerode types.

### CODE REVIEW

**Comment by stuartthomson** [comment]
Thanks for taking a look!

> Cool stuff! Would you mind if we held off on listing containers under a network for a separate PR? I'm not opposed to that aspect, but I would like to consider the experience/implications a bit longer and I don't want that to delay the basic networks view.
> 
> The "new" tree views are very recent and still a little in flux, which is another reason I'd like to delay that aspect. Specifically, I'm just about done adding common settings to control all local views and I'm not sure how that work would jive with listing containers under a network. See this comment for more info: [#983 (comment)](https://github.com/microsoft/vscode-docker/pull/983#issuecomment-501038737)

That's fine with me - it definitely makes sense to wait an see how that ends up. I will add however that one of my major motivations for making these changes was because I kept tabbing out to inspect networks, so from my point of view the feature will definitely be useful - whenever it makes sense to actually implement.

**Comment by stuartthomson** [comment]
Thanks. Just so I'm clear - shall I fix the package.json conflicts?

**Comment by EricJizbaMSFT** [comment]
> Thanks. Just so I'm clear - shall I fix the package.json conflicts?

Yes please!

**Comment by EricJizbaMSFT** [comment]
@stuartthomson can you try again with the merge? [this file](https://github.com/microsoft/vscode-docker/pull/988/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) should only have your network additions and shouldn't have any deletions

**Comment by EricJizbaMSFT** [comment]
@stuartthomson never mind I took care of the merge problems so that I could start work to integrate this with my settings PR https://github.com/microsoft/vscode-docker/pull/989

**Comment by stuartthomson** [comment]
@EricJizbaMSFT Thanks, apologies for the confusion!

**Comment by EricJizbaMSFT** [comment]
Thanks for contributing! Can you create an issue for viewing container information in the Networks view, including your motivation for that: https://github.com/microsoft/vscode-docker/issues/new 

If you want to implement that yourself, I can ping that issue once I merge the settings PR and I could even assign the issue to you. Otherwise we might take care of it if we have time

**Comment by stuartthomson** [comment]
@EricJizbaMSFT I've created the issue. Feel free to ping me, I would be happy to do it.

**Pull request merged**
