### PR TITLE
Enable configuration for View Logs command

### LINKED ISSUE #1505: Configuring command line options for "View Logs" command
Currently, using "View Logs" command means the whole log will be printed to the terminal. It's too much time to wait. Enough to categorize it as a bug. I'd love to be able to tail the log to e.g. 5 lines.

I imagine something like this in viewContainerLogs.ts: ``terminal.sendText(`docker logs ${options} ${node.containerId}`);`` or just ``terminal.sendText(`docker logs -f --tail=5 ${node.containerId}`);``

I'm willing to submit a pr for this.

### PR DESCRIPTION
**Pull request by luka-zitnik**
Adds two configuration options, Follow and Tail, that match -f and --tail command line arguments of "docker logs" command.

Closes #1505.

### CODE REVIEW

**Comment by philliphoff** [comment]
@luka-zitnik Thanks for the PR!  As an update, we're going to have some discussions in the near future about how to more broadly allow for (consistent) customization of the various Docker commands performed by the extension (rather than have totally different solutions for each log vs. run vs. build vs attach command).  Hence, it may take a bit before we can get this PR integrated and/or we may suggest some changes to align with the outcome of those discussions.

**Comment by luka-zitnik** [comment]
@philliphoff OK. I'd love to see what you'll come up with.

**Comment by bwateratmsft** [comment]
@luka-zitnik This will be addressed with #1649, do you want to close this PR?

**Comment by luka-zitnik** [comment]
Yup

**Pull request closed without merging**
