### PR TITLE
Fixed Dockerfile for Go

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
Fixed the entrypoint in the Dockerfile for Go. Before, it was giving an error saying the command was not found.

### CODE REVIEW

**Comment by ItalyPaleAle** [comment]
+ @joshugav

**Comment by ItalyPaleAle** [comment]
I've updated the PR adding another fix to the Go Dockerfile: CTRL+C signals were not sent to the application before. See https://forums.docker.com/t/docker-run-cannot-be-killed-with-ctrl-c/13108/2

**Comment by StephenWeatherford** [comment]
@ItalyPaleAle I'm not seeing any issues with the current version when I try testing with these steps:

	1) Download this application: https://github.com/cloudfoundry-community/simple-go-web-app/archive/master.zip
	2) Extract it into a local folder
	3) Open this local folder inside vscode
	4) Command Palette: "Docker: Add Docker Files to Workspace"
		a. Select "Go" as application platform
		b. Keep default 3000 as the port
        4b) Make changes from https://github.com/Microsoft/vscode-docker/pull/278 to the Dockerfile
	5) Right-click on Dockerfile -> Build Image
		a. Keep default image name: simple-go-web-app-master:latest
	6) Right-click on Images -> simple-go-web-app:master:latest -> Run Interactive
		a. Should see this in terminal:
			
			C:\Temp\simple-go-web-app-master2\simple-go-web-app-master>docker run --rm -it -p 3000:3000 simple-go-web-app-master:latest
			[martini] listening on :3000 (development)
	7) In a web browser, browse to:
		http://localhost:3000/
	8) You should see "Hello World" in the browser
		
What am I missing?  Thanks.

**Comment by ItalyPaleAle** [comment]
I haven't tried with the fix in #278 . I can test again once that's merged.

In any case, please see the second fix for the CTRL+C signal too!

**Comment by ItalyPaleAle** [comment]
Ok, I just texted with the fixed Dockerfile and I can confirm it works. I believe the issues with this PR were likely caused by other changes I had made. Closing it.

**Comment by StephenWeatherford** [comment]
Thanks!

**Pull request closed without merging**
