### PR TITLE
Update version, changelog, notices for 1.12.0

### PR DESCRIPTION
**Pull request by bwateratmsft**

### CODE REVIEW

**Review by karolz-ms — APPROVED** [review]
Ship it!

**Comment by BigMorty** [comment]
1.55 of VS Code just came out, aren't we being a little aggressive in requiring it so soon?

**Comment by bwateratmsft** [comment]
> 1.55 of VS Code just came out, aren't we being a little aggressive in requiring it so soon?

@BigMorty It'll still be two weeks before we ship, but additionally--if the user is still on 1.54- of VSCode, then it will just wait to update the Docker extension. Nothing bad happens.

**Comment by BigMorty** [comment]
Thanks, that works for me!

**Pull request merged**
