### PR TITLE
Make the shell attach command customizable

### PR DESCRIPTION
**Pull request by FredrikFolkesson**
Allows the user to specify the shell command to be used when attaching to containers by using the settings

`docker.attachShellCommand.LinuxContainer` and `docker.attachShellCommand.windowsContainer`

Defaulting to the current commands `/bin/sh` and `powershell`

This closes, or partly closes, #60.
Depending on if you want the user to be able to specify the shell command to run in "runtime" or only using the settings as this PR provides. 
(the former makes the ease of just right clicking a container and pressing `Attach Shell` a bit worse in my opinion since you would then have to specify the attach command anyways)

### CODE REVIEW

**Comment by FredrikFolkesson** [comment]
@chrisdias Are you still on vacation? :)

**Comment by FredrikFolkesson** [comment]
@chrisdias Any change to look at this? :)

**Comment by chrisdias** [comment]
this looks better than https://github.com/Microsoft/vscode-docker/pull/159. Can we close that one and only take this one?

**Comment by FredrikFolkesson** [comment]
Yeah that makes sense

**Pull request merged**
