### PR TITLE
Start, stop and restart multiple containers

### PR DESCRIPTION
**Pull request by allanwright**
Addresses #1453.

Enabled `CanSelectMany` option on `containersTreeView`. Modified `startContainers`, `stopContainers` and `restartContainers` commands to support multi selection.

### CODE REVIEW

**Comment by bwateratmsft** [comment]
@allanwright I have a branch underway to cover this and also all the Remove commands; it has some additional features to prevent from performing actions which are invalid for a node (and would result in errors): https://github.com/microsoft/vscode-docker/tree/bmw/multiselect

**Comment by allanwright** [comment]
@bwateratmsft Thanks for advising of your branch. Should I have been looking somewhere other than #1453 to see that work was already underway and do I close this PR?

**Comment by bwateratmsft** [comment]
@allanwright I was looking at #331 when I started on that branch; I hadn't actually seen #1453. I guess you can close this PR; sorry for the duplication of effort!

**Comment by allanwright** [comment]
@bwateratmsft No worries, it is actually a good opportunity to see how you've implemented similar functionality. I've learned a few things!

**Pull request closed without merging**
