### PR TITLE
adding show logs command to dead containers

### PR DESCRIPTION
**Pull request by FredrikFolkesson**
You want to be able to check logs for dead containers as well
(from the left side context menu)

### CODE REVIEW

**Comment by FredrikFolkesson** [comment]
@chrisdias any chance to look at this? :)

**Comment by chrisdias** [comment]
@FredrikFolkesson hi sorry, its a holiday here, i've been a little slow on the PRs.  Will look asap.

**Comment by chrisdias** [comment]
not sure we need `package.json` in this PR but i'll fix it all up.

**Comment by FredrikFolkesson** [comment]
No problem, enjoy your holiday :)

I added the command in the package.json as the others were (for reading logs on online containers etc) and since i changed the package.json I guess I need the new package-lock.json? Or I have misunderstood something as well.

**Pull request merged**
