### PR TITLE
feat: add image property for better organization

### PR DESCRIPTION
**Pull request by yoyoys**
I'm using Google Cloud and the repository path is so mess up and useless like this:
old

And I've add `RegistryAndPath` and `RepositoryNameShort` and to filter them like this:
better

The code is tested and pass all the built-in testes, 
and no effect to current users until they use new image property,
hope this is helpful for everyone. Thanks

### CODE REVIEW

**Comment by yoyoys** [comment]
@microsoft-github-policy-service agree

**Review by bwateratmsft — APPROVED** [review]
Code looks good to me. @fiveisprime any objections to this from PM perspective?

**Review by OGCJM11 — APPROVED** [review]

**Comment by fiveisprime** [comment]
No objection from me, looks good. :shipit:

**Comment by bwateratmsft** [comment]
Thanks for the contribution @yoyoys!

**Comment by yoyoys** [comment]
@bwateratmsft Would you add this to milestones? :)

**Comment by bwateratmsft** [comment]
Done! Not sure when it will be shipping though, given the holidays.

**Pull request merged**
