### PR TITLE
Remove files written notification

### LINKED ISSUE #515: notification overload
when i "add dockerfiles to the workspace", i get a prompt that tells me files were added to my workspace.  This seems unnecessary:

* the command i executed indicated that i wanted to add files to my workspace
* i can see that new files were added because they show up in my explorer
* i can see that files were added because i am using source code control

For the past few years i don't remember anyone complaining that this was an issue, but now i have to click again to dismiss the notification.

### PR DESCRIPTION
**Pull request by StephenWeatherford**
Fixes #515

### CODE REVIEW

**Comment by chrisdias** [comment]
i dont see any reason to open it... again, i'm probably under SCC so i'll see the new files added to the workspace in the explorer pretty quickly.

**Comment by EricJizbaMSFT** [comment]
I was only suggesting we open the Dockerfile _if it's useful_ (not purely as a notification). I'm coming from experience with the functions extension where I think it's pretty fair to assume users will edit their new 'index.js' file or set a breakpoint. If users never interact with their Dockerfile, then I agree it's more noise than it's worth.

Back to the notification, though - I do want to make sure we're "designing for the user" and not "designing for the demo". When I'm dogfooding VS Code I hardly ever dismiss info messages (that don't have a button) because they disappear in 10 seconds anyways. I literally don't care about them. However, I can imagine being annoyed during a demo where "Add docker files" was the main attraction and I wanted it to be spotless.

I can't vouch for Docker, but we _have_ received feedback in the functions extension that people want  feedback once files have been added. The entry point for 'Create new project' and 'Create function' is in the Azure view, so users have to explicitly switch to the SCC or file view to notice if things were added. New users have said they end up clicking the button multiple times before they thought to check the other views.

**Comment by StephenWeatherford** [comment]
Personally I like the idea of opening the Dockerfile.  I would expect most users to at least check it over if not make modifications.  And if the next step is to build, that's easier with the file open (right-click -> Build Image).

**Comment by chrisdias** [comment]
i can see why you would want to open the `Dockerfile`, so I would be ok with that.  i just have not seen any customer feedback that suggests its a problem (as you have with functions).

**Pull request merged**
