### PR TITLE
Switch from travis ci to azure pipelines

### PR DESCRIPTION
**Pull request by EricJizbaMSFT**
Mostly copied from [functions](https://github.com/Microsoft/vscode-azurefunctions) repo. Unfortunately tests weren't working on Mac or Windows agents by default so I disabled them and filed an issue for someone (maybe me if I get bored? Maybe Stephen?) to address separately: https://github.com/Microsoft/vscode-docker/issues/606

### CODE REVIEW

**Comment by grhm** [comment]
@EricJizbaMSFT Does the azure pipeline work now?  Only it looks like all PR builds are failing with permissions issues?  (Looking at the last 3 builds [here](https://dev.azure.com/ms-azuretools/AzCode/_build?definitionId=8))

**Comment by EricJizbaMSFT** [comment]
@grhm yeah I'll look into it. Builds are working from this repo - just not from other forks

**Comment by grhm** [comment]
Did you want me to raise an issue for it, or is my comment here enough?  Not sure of the etiquette here...

**Comment by EricJizbaMSFT** [comment]
In terms of etiquette on issues vs comments: it depends. If you want something fixed then an issue is generally better because it's harder for us to accidentally lose/forget. In this case an issue isn't necessary because I already have a PR out: https://github.com/Microsoft/vscode-docker/pull/610

**Pull request merged**
